<?php

/**
 * @file
 * Functions to support theming in the rikstarter theme.
 */

/**
 * Implements hook_preprocess_page().
 */
function rikstarter_preprocess_page(array &$variables) {
  $variables['test'] = [
    '#test' => 'test'
  ];
}

/**
 * Implements hook_preprocess_region().
 */
function rikstarter_preprocess_region(array &$variables) {
  $variables['test'] = [
    '#test' => 'test'
  ];
}
